import type { Trade, ChipCategory } from '~/types'

export const DEFAULT_MOCK_CHIPS: ChipCategory[] = [
  {
    id: 'Strategies',
    values: ['Breakout', 'Pullback', 'Gap & Go', 'VWAP Bounce', 'Mean Reversion', 'Trend Continuation', 'Support/Resistance']
  },
  {
    id: 'Setups',
    values: ['A+ High Probability', 'Flag Break', 'Double Bottom', 'Opening Range Breakout', 'Liquidity Sweep', 'Retest']
  },
  {
    id: 'Emotions',
    values: ['Disciplined', 'Calm & Patient', 'Slight FOMO', 'Hesitant', 'Confident', 'Revenge Tendency', 'Fully Focused']
  },
  {
    id: 'Timeframe',
    values: ['1m', '5m', '15m', '1h', '4h', 'Daily', 'Weekly']
  },
  {
    id: 'RiskProfile',
    values: ['1R Conservative', '2R Standard', '3R+ Aggressive', 'Scaled Entry']
  }
]

export const DEFAULT_MOCK_SETTINGS = {
  chip_layout: {
    panels: [
      { id: 'Strategies', title: 'Strategies', chip_ids: ['Strategies'] },
      { id: 'Setups', title: 'Setups', chip_ids: ['Setups'] },
      { id: 'Emotions', title: 'Emotions & Psychology', chip_ids: ['Emotions'] },
      { id: 'Timeframe', title: 'Timeframe', chip_ids: ['Timeframe'] }
    ]
  },
  strategyChecklists: {
    'Breakout Strategy': {
      rules: [
        { description: 'Daily chart in confirmed uptrend (above 20 EMA)', weight: 25, isMandatory: true },
        { description: 'Volume on breakout > 1.5x 20-day average', weight: 25, isMandatory: true },
        { description: 'Defined risk level & stop loss placed prior to entry', weight: 25, isMandatory: true },
        { description: 'Risk to reward ratio >= 2:1', weight: 15, isMandatory: false },
        { description: 'Catalyst or news confirmation aligned', weight: 10, isMandatory: false }
      ],
      tiers: [
        { label: 'Tier 1 (A+)', threshold: 90 },
        { label: 'Tier 2 (B)', threshold: 75 },
        { label: 'Tier 3 (C)', threshold: 60 }
      ]
    },
    'Pullback Strategy': {
      rules: [
        { description: 'Key support level retested on lower volume', weight: 30, isMandatory: true },
        { description: 'Bullish reversal candlestick pattern formed', weight: 30, isMandatory: true },
        { description: 'Risk clearly defined below support swing low', weight: 20, isMandatory: true },
        { description: 'Market index (SPY/QQQ) confirming direction', weight: 20, isMandatory: false }
      ],
      tiers: [
        { label: 'Tier 1 (A+)', threshold: 85 },
        { label: 'Tier 2 (B)', threshold: 70 },
        { label: 'Tier 3 (C)', threshold: 50 }
      ]
    }
  }
}

export function getMockTrades(): Trade[] {
  const seedTrades: Array<Partial<Trade> & { [key: string]: any }> = [
    // 2026 Trades
    {
      id: 'demo-1',
      date: '02/20/2026',
      pair: 'NVDA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 132.50,
      exitPrice: 144.20,
      size: 150,
      pnl: 1755.00,
      mae: -0.85,
      mfe: 12.10,
      checklistScore: 95,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Confident'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'A+ High Probability,Opening Range Breakout',
      Notes: 'Strong breakout above multi-week resistance after earnings guidance catalyst. Scaled out near psychological $145 level.'
    },
    {
      id: 'demo-2',
      date: '02/18/2026',
      pair: 'TSLA',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 215.00,
      exitPrice: 204.50,
      size: 100,
      pnl: 1050.00,
      mae: -1.20,
      mfe: 11.50,
      checklistScore: 88,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Liquidity Sweep',
      Notes: 'Failed breakout above 200 SMA on daily, strong rejection wick. Captured full intraday flush to VWAP.'
    },
    {
      id: 'demo-3',
      date: '02/14/2026',
      pair: 'AAPL',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 228.00,
      exitPrice: 224.50,
      size: 100,
      pnl: -350.00,
      mae: -3.80,
      mfe: 0.90,
      checklistScore: 65,
      tier: 'Tier 3 (C)',
      rulesFollowed: false,
      mentalCategory: 'B',
      emotions: ['Slight FOMO'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Flag Break',
      Notes: 'Chased entry slightly late near top of range. Cut loss quickly according to risk rules.'
    },
    {
      id: 'demo-4',
      date: '02/11/2026',
      pair: 'SPY',
      market: 'Indices',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 585.20,
      exitPrice: 591.80,
      size: 120,
      pnl: 792.00,
      mae: -0.40,
      mfe: 6.90,
      checklistScore: 90,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Fully Focused'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'Key Support Retest',
      Notes: 'Clean bounce off rising 20 EMA on 15m chart. Trend continuation setup during FOMC aftermath.'
    },
    {
      id: 'demo-5',
      date: '02/08/2026',
      pair: 'AMD',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 118.40,
      exitPrice: 125.10,
      size: 180,
      pnl: 1206.00,
      mae: -0.60,
      mfe: 7.20,
      checklistScore: 92,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Confident'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Double Bottom',
      Notes: 'Sympathy rally following sector peer earnings. Held through lunch consolidation without hesitation.'
    },
    {
      id: 'demo-6',
      date: '02/04/2026',
      pair: 'BTC/USD',
      market: 'Crypto',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 94200.00,
      exitPrice: 97800.00,
      size: 0.5,
      pnl: 1800.00,
      mae: -450.00,
      mfe: 3900.00,
      checklistScore: 85,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'Overnight',
      Strategies: 'Trend Continuation',
      Setups: 'Flag Break',
      Notes: 'Weekend consolidation broke to the upside with strong spot market delta.'
    },
    {
      id: 'demo-7',
      date: '01/29/2026',
      pair: 'MSFT',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 422.00,
      exitPrice: 425.50,
      size: 80,
      pnl: -280.00,
      mae: -3.70,
      mfe: 1.10,
      checklistScore: 70,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Hesitant'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Double Top',
      Notes: 'Stopped out as tech sector caught late day bid. Risk was strictly managed.'
    },
    {
      id: 'demo-8',
      date: '01/24/2026',
      pair: 'META',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 640.00,
      exitPrice: 658.50,
      size: 70,
      pnl: 1295.00,
      mae: -1.50,
      mfe: 19.20,
      checklistScore: 96,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Fully Focused'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'A+ High Probability',
      Notes: 'Multi-month all-time-high breakout with heavy institutional volume flow.'
    },
    {
      id: 'demo-9',
      date: '01/20/2026',
      pair: 'EUR/USD',
      market: 'Forex',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 1.0450,
      exitPrice: 1.0380,
      size: 100000,
      pnl: 700.00,
      mae: -0.0015,
      mfe: 0.0078,
      checklistScore: 82,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined'],
      session: 'London',
      Strategies: 'Trend Continuation',
      Setups: 'Retest',
      Notes: 'ECB rate decision dovish reaction, clean continuation on 1h timeframe.'
    },
    {
      id: 'demo-10',
      date: '01/16/2026',
      pair: 'GOOGL',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 182.00,
      exitPrice: 180.20,
      size: 150,
      pnl: -270.00,
      mae: -2.10,
      mfe: 0.80,
      checklistScore: 60,
      tier: 'Tier 3 (C)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Slight FOMO'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Opening Range Breakout',
      Notes: 'Failed morning breakout. Respected stop loss without hesitation.'
    },
    {
      id: 'demo-11',
      date: '01/12/2026',
      pair: 'AMZN',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 208.50,
      exitPrice: 216.00,
      size: 130,
      pnl: 975.00,
      mae: -0.70,
      mfe: 8.10,
      checklistScore: 91,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Confident', 'Calm & Patient'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'VWAP Bounce',
      Notes: 'Textbook VWAP reclaim on 5m chart with increasing volume.'
    },
    {
      id: 'demo-12',
      date: '01/08/2026',
      pair: 'NVDA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 122.00,
      exitPrice: 129.50,
      size: 160,
      pnl: 1200.00,
      mae: -0.90,
      mfe: 8.00,
      checklistScore: 94,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Flag Break',
      Notes: 'CES announcement momentum run.'
    },
    {
      id: 'demo-13',
      date: '01/05/2026',
      pair: 'TSLA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 240.00,
      exitPrice: 235.80,
      size: 90,
      pnl: -378.00,
      mae: -4.50,
      mfe: 1.20,
      checklistScore: 72,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Hesitant'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Opening Range Breakout',
      Notes: 'Delivery numbers met with sell-the-news reaction. Cut trade cleanly.'
    },
    // Late 2025 Trades (giving historical depth)
    {
      id: 'demo-14',
      date: '12/28/2025',
      pair: 'SPY',
      market: 'Indices',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 572.00,
      exitPrice: 578.40,
      size: 100,
      pnl: 640.00,
      mae: -0.30,
      mfe: 6.70,
      checklistScore: 89,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'New York',
      Strategies: 'Trend Continuation',
      Setups: 'Retest',
      Notes: 'Santa Claus rally seasonal strength.'
    },
    {
      id: 'demo-15',
      date: '12/22/2025',
      pair: 'AAPL',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 220.00,
      exitPrice: 227.80,
      size: 110,
      pnl: 858.00,
      mae: -0.80,
      mfe: 8.20,
      checklistScore: 92,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'A+ High Probability',
      Notes: 'Holiday shopping cycle optimism breakout.'
    },
    {
      id: 'demo-16',
      date: '12/17/2025',
      pair: 'AMD',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 128.00,
      exitPrice: 131.20,
      size: 100,
      pnl: -320.00,
      mae: -3.50,
      mfe: 0.50,
      checklistScore: 68,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Hesitant'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Liquidity Sweep',
      Notes: 'Semiconductor rally remained stronger than anticipated. Exited at stop.'
    },
    {
      id: 'demo-17',
      date: '12/12/2025',
      pair: 'NVDA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 115.00,
      exitPrice: 122.30,
      size: 150,
      pnl: 1095.00,
      mae: -0.50,
      mfe: 7.60,
      checklistScore: 95,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Confident', 'Fully Focused'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'VWAP Bounce',
      Notes: 'High volume reversal at previous day high support.'
    },
    {
      id: 'demo-18',
      date: '12/05/2025',
      pair: 'BTC/USD',
      market: 'Crypto',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 88500.00,
      exitPrice: 92400.00,
      size: 0.4,
      pnl: 1560.00,
      mae: -300.00,
      mfe: 4100.00,
      checklistScore: 90,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined'],
      session: 'Overnight',
      Strategies: 'Breakout',
      Setups: 'Flag Break',
      Notes: 'Institutional ETF inflows accelerating.'
    },
    {
      id: 'demo-19',
      date: '11/28/2025',
      pair: 'TSLA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 210.00,
      exitPrice: 221.50,
      size: 90,
      pnl: 1035.00,
      mae: -1.10,
      mfe: 12.00,
      checklistScore: 88,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Double Bottom',
      Notes: 'Clean breakout of descending channel on daily chart.'
    },
    {
      id: 'demo-20',
      date: '11/21/2025',
      pair: 'META',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 598.00,
      exitPrice: 602.50,
      size: 60,
      pnl: -270.00,
      mae: -4.80,
      mfe: 1.00,
      checklistScore: 62,
      tier: 'Tier 3 (C)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Slight FOMO'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Retest',
      Notes: 'Market breadth remained too strong to short megacap tech.'
    },
    {
      id: 'demo-21',
      date: '11/15/2025',
      pair: 'QQQ',
      market: 'Indices',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 495.00,
      exitPrice: 504.20,
      size: 100,
      pnl: 920.00,
      mae: -0.60,
      mfe: 9.80,
      checklistScore: 93,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Confident'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'A+ High Probability',
      Notes: 'Tech sector leadership leading broader market to new monthly highs.'
    },
    {
      id: 'demo-22',
      date: '11/08/2025',
      pair: 'MSFT',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 410.00,
      exitPrice: 418.90,
      size: 80,
      pnl: 712.00,
      mae: -0.75,
      mfe: 9.30,
      checklistScore: 87,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'VWAP Bounce',
      Notes: 'Cloud segment growth optimism providing steady bid.'
    },
    {
      id: 'demo-23',
      date: '11/02/2025',
      pair: 'AMZN',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 195.00,
      exitPrice: 198.80,
      size: 90,
      pnl: -342.00,
      mae: -4.00,
      mfe: 0.60,
      checklistScore: 65,
      tier: 'Tier 3 (C)',
      rulesFollowed: false,
      mentalCategory: 'C',
      emotions: ['Revenge Tendency'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Liquidity Sweep',
      Notes: 'Fought trend intraday. Good lesson on avoiding counter-trend shorts during strong momentum.'
    },
    {
      id: 'demo-24',
      date: '10/26/2025',
      pair: 'NVDA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 108.00,
      exitPrice: 114.60,
      size: 150,
      pnl: 990.00,
      mae: -0.40,
      mfe: 6.90,
      checklistScore: 94,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Confident'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'Opening Range Breakout',
      Notes: 'Heavy pre-market volume confirming strong continuation.'
    },
    {
      id: 'demo-25',
      date: '10/18/2025',
      pair: 'EUR/USD',
      market: 'Forex',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 1.0780,
      exitPrice: 1.0865,
      size: 100000,
      pnl: 850.00,
      mae: -0.0012,
      mfe: 0.0090,
      checklistScore: 84,
      tier: 'Tier 2 (B)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined'],
      session: 'London',
      Strategies: 'Trend Continuation',
      Setups: 'Retest',
      Notes: 'US Dollar weakness following CPI inflation print.'
    },
    {
      id: 'demo-26',
      date: '10/11/2025',
      pair: 'AAPL',
      market: 'Stocks',
      direction: 'Long',
      status: 'Closed',
      entryPrice: 212.00,
      exitPrice: 219.40,
      size: 100,
      pnl: 740.00,
      mae: -0.50,
      mfe: 7.80,
      checklistScore: 91,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Fully Focused'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'VWAP Bounce',
      Notes: 'Morning gap fill completed, perfect reversal off 50 SMA on 5m.'
    },
    {
      id: 'demo-27',
      date: '10/04/2025',
      pair: 'TSLA',
      market: 'Stocks',
      direction: 'Short',
      status: 'Closed',
      entryPrice: 232.00,
      exitPrice: 236.40,
      size: 70,
      pnl: -308.00,
      mae: -4.80,
      mfe: 0.90,
      checklistScore: 66,
      tier: 'Tier 3 (C)',
      rulesFollowed: true,
      mentalCategory: 'B',
      emotions: ['Hesitant'],
      session: 'New York',
      Strategies: 'Mean Reversion',
      Setups: 'Double Top',
      Notes: 'Robotaxi event hype caused sudden squeeze. Cut immediately at invalidation point.'
    },
    // Active Open Trades
    {
      id: 'demo-28',
      date: '02/24/2026',
      pair: 'NVDA',
      market: 'Stocks',
      direction: 'Long',
      status: 'Open',
      entryPrice: 141.20,
      size: 120,
      checklistScore: 96,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Disciplined', 'Confident'],
      session: 'New York',
      Strategies: 'Breakout',
      Setups: 'A+ High Probability',
      Notes: 'Holding runner position above $140 level for continuation target $150.'
    },
    {
      id: 'demo-29',
      date: '02/25/2026',
      pair: 'SPY',
      market: 'Indices',
      direction: 'Long',
      status: 'Open',
      entryPrice: 596.50,
      size: 100,
      checklistScore: 92,
      tier: 'Tier 1 (A+)',
      rulesFollowed: true,
      mentalCategory: 'A',
      emotions: ['Calm & Patient'],
      session: 'New York',
      Strategies: 'Pullback',
      Setups: 'VWAP Bounce',
      Notes: 'Entered on 15m pullback to daily VWAP with stop under day low.'
    }
  ]

  return seedTrades.map((t, idx) => ({
    createdAt: new Date(t.date || '01/01/2026').toISOString(),
    ...t
  })) as Trade[]
}
